# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('no', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquote_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quote_name',
            new_name='quote_text',
        ),
        migrations.AddField(
            model_name='approvedquote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='no.Quote'),
        ),
    ]
