# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no', '0003_auto_20160115_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_likes',
            field=models.IntegerField(default=0),
        ),
    ]
