# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('no', '0005_auto_20160120_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_valid',
            field=models.BooleanField(default=False),
        ),
    ]
